[project]
name = "ap3persistencia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "motor>=3.7.0",
    "odmantic>=1.0.2",
    "ruff>=0.9.7",
]
